#! /usr/bin/env ruby

require 'yaml'

def dir_blacklist
  ["css", "sass", "script"]
end

def useless?(f)
  f.start_with?("_") ||
    f.start_with?(".") ||
    !File.directory?(f) ||
    dir_blacklist.include?(f)
end

def get_gif_dirs
  Dir.foreach(".").map { |f| f unless useless?(f) }.compact
end

def liquid_info_for_file(dir, filename)
  path = File.join(filename)
  {
    "path"          => path,
    "modified_time" => File.mtime(path).to_i,
    "extname"       => File.extname(path)
  }
end

dirs = get_gif_dirs
files = []

dirs.each do |dir|
  Dir.glob("#{dir}/*.gif") do |gif|
    files << liquid_info_for_file(dir, gif)
  end
end

File.open("_data/static_files.yml", 'w') { |f| f.write(YAML.dump(files)) }
